import type { Metadata } from "next";
import { IBM_Plex_Sans_KR, Josefin_Sans } from "next/font/google";
import "@/styles/globals.css";

const ibmPlexSansKr = IBM_Plex_Sans_KR({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400", "600", "700"],
});
const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`h-full ${ibmPlexSansKr.className} ${josefinSans.className} font-body`}
      >
        {children}
      </body>
    </html>
  );
}
